namespace Univ.Hi_Student_Affairs.EntityFrameworkCore;

public abstract class Hi_Student_AffairsEntityFrameworkCoreTestBase : Hi_Student_AffairsTestBase<Hi_Student_AffairsEntityFrameworkCoreTestModule>
{

}
